### ISSUE TITLE
Vavr's Map value extaction is not supported

### ISSUE THREAD

**Issue by cardil** [vavr-io/vavr-beanvalidation2#2]
Bean Validation when operation on JVM Map properly extracts a value from Map and validate it. When using a Vavr Map with validation on key or value exception is thrown:

```
javax.validation.ConstraintDeclarationException: HV000197: No value extractor found for type parameter 'K' of type io.vavr.collection.Map.
```

or 

```
javax.validation.ConstraintDeclarationException: HV000197: No value extractor found for type parameter 'V' of type io.vavr.collection.Map.
```

Extraction of Map keys and values should be supported.

**Comment by alwins0n** [comment]
Huh, good catch. I didn't expect this to happen since `Map<K, V>` extends (via `Traversable` and `Value`) `java.lang.Iterable<Tuple2<K, V>>` for which extractors exists.

Thanks for the PR. It should be possible to find the solution with a bit of debugging. If you provide one I am happy to merge, otherwise I'll try to fix as soon as I have time
